{
 "title": "API Gateway V2",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "route", "label": "Route", "query": { "query": "label_values(route)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count{route=~\"$route\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Integration Latency / Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "IntegrationLatency{route=~\"$route\"}",
     "legendFormat": "{{route}}"
    },
    {
     "expr": "Latency{route=~\"$route\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_4xx{route=~\"$route\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Error 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_5xx{route=~\"$route\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Error percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "error_percent{route=~\"$route\"}",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}